version: '3'

services:
    php:
        container_name: "php"
        build:
            context: ./build/php
        environment:
            - APP_ENV=dev
            - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
        volumes:
            - ./app:/var/www
        networks:
            - backend

    app:
        container_name: "app"
        build:
            context: ./build/nginx
        volumes:
            - ./app:/var/www
            - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./build/logs:/var/log
        depends_on:
            - php
        ports:
            - "80:80"
        networks:
            - backend

    db:
        image: mariadb/server
        container_name: "db"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: dynamix
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - backend
        ports:
            - '3306:3306'
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: "PHPMyAdmin"
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db:3306
            MYSQL_ROOT_PASSWORD: rootpassword
            PMA_PORT: 3306
        networks:
            - backend


networks:
    backend:
        driver: bridge

